name: safe_json
description: "Primary purpose of this library is to find out backend error(incomplete data) at the first time."
version: 1.0.9
repository: https://github.com/ChadCN/safe_json

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.16.8

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
