name: safe_json
description: "A happy way to parse JSON in Dart."
version: 1.0.0
repository: https://github.com/ChadCN/safe_json

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
